GET http://localhost:3305/api/users

###
GET http://localhost:3000/api/users/eunewoo7

###
POST http://localhost:3305/api/users
Content-Type: application/json

{
    //"_id": "",
    "user_id": "eunewoo6",
    "password": "6b115c393d2c543157778a1f74eb2b446632c44fd0a54542cd000b105d7165",
    "user_name": "King_eunwoo",
    "user_email": "ewchoi98@naver.com",
    "address_f": "서울시 송파구 문정로83",
    "address_l": "122동 602호"
    //"img": ""
}

###
PUT http://localhost:3000/api/users
Content-Type: application/json

{
    //"id": "63bf8013da04d529e5360207",
    "user_id": "eunewoo",
    "password": "undefined",
    "user_name": "eunwoo_dev",
    "user_email": "ewchoi98@naver.com",
    "address_f": "서울시 송파구",
    "address_l": "122동",
    "img": "undefined"
}

###
GET http://localhost:3000/api/questions/eunewoo5

###
POST http://localhost:3000/api/questions
Content-Type: application/json

{
  "user_id": "63be8eeff07a096309001556",
  "question": "Do you satisfy your day?",
  "question_selection": ["Perfect", "SoSo", "Nah"],
  "question_type": "multiple choice3"
}

###
PUT http://localhost:3305/api/questions
Content-Type: application/json

{
  "user_id": "eunewoo",
  "question": "Do you satisfy your day3?",
  "question_selection": ["Perfect", "SoSo", "Bad"],
  "question_type": "multiple choice",
  "question_answers": ["put"]
}

###
DELETE http://localhost:3305/api/questions/eunewoo&Do you satisfy your day2?
